### ISSUE TITLE
Tracking issue: improve test coverage

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1053]
### Component

Forge

### Describe the feature you would like

- [x] more `forgetest!` test for the `forge test` command
- [x] additional solc selection test to test all scenarios: (autodetect, pin version, use custom install)
- [x] verify contract test
- [x] full coverage logging tests
- [ ] ...

**Comment by onbjerg** [comment]
Relevant:

- [ ] https://github.com/gakonst/foundry/issues/968
- [ ] https://github.com/gakonst/foundry/issues/967
- [ ] https://github.com/gakonst/foundry/issues/966
- [ ] https://github.com/gakonst/foundry/issues/932

**Comment by mattsse** [comment]
closing this as test coverage has grown quite a bit
