### ISSUE TITLE
meta: `forge init` improvements

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#1132]
### Component

Forge

### Describe the feature you would like

Here are some small changes that I think would improve the quality of `forge init`:

- [x] Move `test` to the root instead of nested within `src`. This scales better for large projects and is a little more explicit about where tests are
- [ ] Minimize `foundry.toml` by only including things users are more likely to change. For example, most users don't need to worry about remappings so those can be removed (I think they may have been already?). Most people don't change the folder structure so that can probably be removed too. Include a `default` and `ci` profile that specify e.g. 100 and 10,000 runs respectively
- [ ] Include a strong default github workflow with multiple jobs
    1. [ ] Runs `FOUNDRY_PROFILE=ci forge test`
    2. [ ] Sweeps over pragmas with the default profile. Dependent on https://github.com/gakonst/foundry/issues/1131
    3. [x] Verifies all non-test contracts are below the size limit. Dependent on https://github.com/gakonst/foundry/issues/1133
- [x] The default pragma is `0.8.10`. This should be bumped and loosened to `^0.8.13`

I can see an argument against (3) since not everyone uses github. But it's very rare I come across gitlab or bitbucket repos, and it's easy to remove the workflow, so I think this tradeoff is worth it

**Comment by dmfxyz** [comment]
For (3), what dispatch triggers should the workflow have? I agree it would be good to include, but suggest that since it's being automatically added, only a `workflow_dispatch` should be included by default. Those running in private repos or with self-hosted runners may be sensitive to gha usage.

**Comment by DanielVF** [comment]
I'm all for moving the test directory up a level.

**Comment by onbjerg** [comment]
I agree, moving the tests to root makes sense and it wouldn't break anything since we would still run tests in `src` as we do now (pinging @mattsse for confirm on that)

**Comment by mds1** [comment]
Just noting here that "Verifies all non-test contracts are below the size limit" can now be implemented

**Comment by sambacha** [comment]
Is it possible to first have an empty commit then the actual forge init commit when creating a repo? 

Maybe also a flag for --makefile/--justfile or even --template-url

**Comment by onbjerg** [comment]
Yes, `forge init --no-commit`. Please refer to the docs: https://book.getfoundry.sh/reference/forge/forge-init.html#vcs-options

**Comment by mds1** [comment]
Going to close this issue. I think the existing simple `forge init` is sufficient, and there are now many third party templates that each have their own defaults and opinions. Some examples:
- https://github.com/ScopeLift/foundry-template
- https://github.com/PaulRBerg/foundry-template
- https://github.com/ZeframLou/foundry-template
- https://github.com/hifi-finance/foundry-template
- https://github.com/refcell/femplate
- https://github.com/transmissions11/foundry-template
