### ISSUE TITLE
Restructure evm crate

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1725]
### Component

Forge, Cast, Anvil

### Describe the feature you would like

the `evm` crate currently contains supporting types for working with `revm`, this includes

* inspectors (for revm `Inspector` trait used during testing )
* executor (helper abstraction over revm::DatabaseRef)
* fuzzing
* tracing
* fork

the executor module also contains the fork and its related types.

The main abstraction over various `revm::Database` types is called `Backend`, this naming discrepancy stems from legacy sputnik support, where everything was called `Backend`.

the anvil crate also its own fork database-related types that should be moved to evm directly (#1715).

The evm crate is rather beefy atm and takes a bit to compile, some features are also not needed by anvil (fuzzing, most inspectors).

I'd propose the following changes

- [ ] restructure the `executor` module: move fork and database related types to their own module
- [ ] feature gate fuzzing + inspectors (only if possible and not too much refactoring effort)

optional
- [ ] rename `Backend` -> `Database`, to fit revm's convention, however I kinda like `Backend` as it's broader

**Comment by mattsse** [comment]
no longer relevant after overhaul done with multifork support
