### ISSUE TITLE
Add a solidity formatter

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#185]
Ideally, this should be a subcommand like `forge fmt <Options...>`

Rules and settings should be on par with https://github.com/prettier-solidity/prettier-plugin-solidity

#176 contains a basic design skeleton for how this could look like.

Like `prettier-solidity`, we'd parse the AST (with [`solang`](https://github.com/hyperledger-labs/solang/tree/main/src/parser)'s parser) then convert all nodes back to text but formatted, according to the configured rules.

## Tasks left for #176
- [x] Implement `Visitable` for all `solang` AST nodes
- [x] Implement all event handlers in the `Formatter` visitor that then convert a node to text
- [x] Ensure formatting is lossless
- [ ] supports `prettier-solidity` rules
- [x] Add an `fmt` subcommand for the cli app

**Comment by odyslam** [comment]
Not sure if relevant here or it should be its own feature, but it would be very nice if the formatted could:
- Automatically remove testing libraries import statements 
- Automatically remove any `emit log`/`console.log` statements
- Automatically remove anything marked by some specific comment statement (like hadolint, shellhint, etc.)

**Comment by onbjerg** [comment]
@rkrasiuk & @jpopesculian what is the status on this issue in particular? There are a few fmt related issues that are very broad, I'm not sure if they have been solved or if we should close and split into more actionable issues?

**Comment by rkrasiuk** [comment]
>  supports prettier-solidity rules
i didn't check that list item, because i don't think we wanna support all those rules. i'd prefer to add new ones per request.  

vote close

**Comment by onbjerg** [comment]
Will close, if we want to add prettier-solidity rules we can open a separate issue for that
