### ISSUE TITLE
Tracking: Coverage

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1961]
There's still some missing features and improvements for coverage:

**Data/functionality**

- [x] #1962
- [x] #1963
- [x] #1964
- [x] #1967
- [x] #1965

**User facing**

- [x] #1966

**Misc**

- [x] #1969
- [ ] #1968

**Comment by aahna-ashina** [comment]
@onbjerg When I run `forge coverage` at https://github.com/nation3/court, I get this error:

```
could not find anchor: no matching instruction in range CollateralAgreementFramework:3834:2:7
```

```

forge coverage 
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in lib/solmate/foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [intense] found in lib/solmate/foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
[⠒] Compiling...
[⠒] Compiling 11 files with 0.8.14
[⠑] Solc 0.8.14 finished in 992.33ms
Compiler run successful
Analysing contracts...
Error: 
could not find anchor: no matching instruction in range CollateralAgreementFramework:3834:2:7
```

Does `could not find anchor` mean that we are missing some code coverage configuration in our project?

```
forge --version
forge 0.2.0 (37e4376 2022-07-16T00:05:51.461078Z)
```

**Comment by onbjerg** [comment]
Please check the other issues on coverage - this is not on your side, but coverage is not stable yet, so there are edge cases that are not covered. This is one edge case where it could not find an opcode that matches the source range, so we fail and return instead of showing a potentially incorrect coverage report

**Comment by aahna-ashina** [comment]
@onbjerg Is there a way to exclude files/folders when running `forge coverage`?

**Comment by elenadimitrova** [comment]
@aahna-ashina I had the same question and what I ended up doing is instead exclude them in `codecov.yml` instead with:
```
ignore:
  - "./tests/"
 ```

**Comment by paulrberg** [comment]
Thanks @elenadimitrova, great idea to ignore the tests in Codecov directly.

However, it should be possible to do this with Forge itself - ideally, there would be a `--ignore` flag in the `forge coverage` command.

I created an issue to track this as a feature request: https://github.com/foundry-rs/foundry/issues/4006.

**Comment by PaulRBerg** [comment]
@elenadimitrova, does the ignore config work for you on Codecov?

I just added a `codecov.yml` file at the root of my repository, and I also added the `gcov_ignore` input to the Codecov GitHub Action, like this:

```yml
- name: "Upload coverage report to Codecov"
  uses: "codecov/codecov-action@v3"
  with:
    files: "./lcov.info"
    gcov_ignore: "test"
```

But I'm still seeing the `test` directory reported on Codecov:

<img width="1600" alt="Screenshot 2023-02-06 at 4 22 17 PM" src="https://user-images.githubusercontent.com/8782666/216997043-88bcf581-a31b-4c46-9148-204f0d7ee681.png">

Am I doing something wrong?

**Comment by PaulRBerg** [comment]
I have recently discovered several bugs in the coverage command. Posting here for cross-reference:

- [ ] https://github.com/foundry-rs/foundry/issues/4294
- [ ]  https://github.com/foundry-rs/foundry/issues/4305
- [ ]  https://github.com/foundry-rs/foundry/issues/4309
- [ ]  https://github.com/foundry-rs/foundry/issues/4310
- [ ]  https://github.com/foundry-rs/foundry/issues/4311
- [ ]  https://github.com/foundry-rs/foundry/issues/4314
- [ ]  https://github.com/foundry-rs/foundry/issues/4315
- [ ]  https://github.com/foundry-rs/foundry/issues/4316

**Comment by zerosnacks** [comment]
Closing in favor of #4442 as updated metatracking ticket, includes the bugs stated in https://github.com/foundry-rs/foundry/issues/1961#issuecomment-1427113699
