### ISSUE TITLE
Tracking issue meaningful error messages

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#275]
This is a tracking issue to add more meaningful messages for certain errors

- [x] `No such file ...`
   - [x] check if the cwd deviates from the root and display hint to add the `--root .`
- [ ] add file info when `Missing pragma from solidity file`
- [ ] explain incompatible versions in autodetection

...

**Comment by onbjerg** [comment]
Going to close this since I think you already addressed the messages listed in the issue :smile:
