### ISSUE TITLE
meta: invariant testing features

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3412]
### Component

Forge

### Describe the feature you would like

This issue simply aggregates the issues that would improve invariant testing (and some related to fuzz testing too). In no particular order:

- [ ] 1. https://github.com/foundry-rs/foundry/issues/3062
- [ ] 2. https://github.com/foundry-rs/foundry/issues/3005
- [ ] 3. https://github.com/foundry-rs/foundry/issues/2986
- [ ] 4. https://github.com/foundry-rs/foundry/issues/2963
- [x] 5. https://github.com/foundry-rs/foundry/issues/3400
- [ ] 6. https://github.com/foundry-rs/foundry/issues/2985
- [ ] 7. https://github.com/foundry-rs/foundry/issues/2962
- [ ] 8. https://github.com/foundry-rs/foundry/issues/2551
- [ ] 9. https://github.com/foundry-rs/foundry/issues/2552
- [ ] 10. https://github.com/foundry-rs/foundry/issues/1350
- [ ] 11. https://github.com/foundry-rs/foundry/issues/1578
- [ ] 12. https://github.com/foundry-rs/foundry/issues/2846
- [ ] 13. https://github.com/foundry-rs/foundry/issues/3390
- [ ] 14. https://github.com/foundry-rs/foundry/issues/3277 (listing this as a generic issue for implementing additional invariant techniques/strategies)
- [ ] 15. https://github.com/foundry-rs/foundry/issues/3411
- [ ] 16. https://github.com/foundry-rs/foundry/issues/3452
- [ ] 17. https://github.com/foundry-rs/foundry/issues/3521
- [ ] 18. https://github.com/foundry-rs/foundry/issues/585
- [ ] 19. https://github.com/foundry-rs/foundry/issues/3607
- [ ] 20. https://github.com/foundry-rs/foundry/issues/4190
- [ ] 21. https://github.com/foundry-rs/foundry/issues/4352
- [ ] 22.  https://github.com/foundry-rs/foundry/issues/4300
- [ ] 23. https://github.com/foundry-rs/foundry/issues/4287
- [ ] 24. https://github.com/foundry-rs/foundry/issues/4178
- [ ] 25. https://github.com/foundry-rs/foundry/issues/4163
- [ ] 26. Other ways to improve fuzz/invariant tests, like coverage guidance or things mentioned in https://github.com/foundry-rs/foundry/issues/3277

**Comment by lucas-manuel** [comment]
Adding metrics issue as per our discussion @mds1 @gakonst 

https://github.com/foundry-rs/foundry/issues/3607

**Comment by gakonst** [comment]
Caught up with @lucasmanuel @mds1. Let's prioritize: #3005 #2963 #2985 and #2962.

**Comment by mds1** [comment]
Two last requests, lower priority than the above set but still valuable + should be quick ones:
- #2986 would enable better support for multiple, different actors + it's better for the standard usage as well
- #585 to better support long-running campaigns (to have confidence it's not hanging)

**Comment by mds1** [comment]
Closing this in favor of https://github.com/foundry-rs/foundry/issues/4438
