### ISSUE TITLE
Chisel: Feature request meta thread

### ISSUE THREAD

**Issue by devtooligan** [foundry-rs/foundry#3743]
### Component

Other (please describe)

### Describe the feature you would like

context: https://github.com/foundry-rs/foundry/pull/3465#issuecomment-1324259466

**Comment by devtooligan** [comment]
need better ux for unknown commands, maybe a hint if the unkown command matches a !command

![Screen Shot 2022-11-21 at 2 52 54 PM](https://user-images.githubusercontent.com/71567643/203174238-d34a37e1-0148-4cea-a201-b0f7f6606c98.png)

**Comment by devtooligan** [comment]
feature request:
convert unix epoch timestamp to readable date.  maybe the other way around too 
https://www.unixtimestamp.com/

**Comment by devtooligan** [comment]
feature request: 

- more integration with cast. 
- call cast commands directly from chisel so u dont have to leave
- use results of cast commands together with solidity commands (like set the value of some solidity var to the output of a cast cmd)

**Comment by devtooligan** [comment]
nit:
after an error the first new -> prompt is red
![Screen Shot 2022-11-21 at 3 07 50 PM](https://user-images.githubusercontent.com/71567643/203176078-3080b789-ad48-4f01-bac0-38e2362d283f.png)

**Comment by devtooligan** [comment]
feature request:
a listing of local variables and their values

!listvar

myadddy 0x18989013980190890818901
myNumber 0x11 (17)
myString "Yo homie"

**Comment by devtooligan** [comment]
feature request:
convert from 64 bit numbers and back  (also maybe 128 and?)  replaces https://toolkit.abdk.consulting/math#convert-number

**Comment by devtooligan** [comment]
feature request: 
`rightpad(0x123)`
0x123000000000000....000 (32bytes)

**Comment by devtooligan** [comment]
feature request:
i think the return value of anything you enter should be displayed after you type it.

so like:
uint y = 100 - 90

right now does nothing, i want it o display 10

values dont display if the expression is enclosed in (parens)
![Screen Shot 2022-11-21 at 3 48 49 PM](https://user-images.githubusercontent.com/71567643/203180911-9cba4d0a-e56f-46a0-a31d-e48a55c75cd3.png)

**Comment by devtooligan** [comment]
feature request:
ability to list files like doing `ls` from command line -- useful when trying to find ur imports

**Comment by devtooligan** [comment]
i got imports to work.  but the return value of a function called an instantiated contract does not display
![Screen Shot 2022-11-21 at 3 24 17 PM](https://user-images.githubusercontent.com/71567643/203178062-55503f9a-ec5e-4a84-8a37-2077db2a6222.png)

**Comment by devtooligan** [comment]
feature request:
shortcuts, can we make it so you only have to enter the first two letters of the command?
!cl for !clear
!me for !memdump
etc...

maybe someday we can have some kind of global or user based aliases

**Comment by mds1** [comment]
This is a great list, thanks @devtooligan!

One thing that might be helpful is refactoring this issue so the top comment is a checklist with all of these in a list, such as in https://github.com/foundry-rs/foundry/issues/876 and https://github.com/foundry-rs/foundry/issues/3412? This makes it easier to track each request individually, instead of the separate comments. (If you’re feeling really ambitious and want to create separate issues for each then link to them here, even better, but I know that’s tedious so nw)

**Comment by devtooligan** [comment]
@mds1 sure.  i should have some time to do this next week.  for now it was just a quick dump to clean up the pr.  cheers!

**Comment by mds1** [comment]
Awesome thanks! 🙌

**Comment by clabby** [comment]
Thanks for the feedback @devtooligan, great suggestions & super useful! Have just cleaned up the README for review, so posting the existing checklist here:

## Checklist

- [x] REPL functionality
  - [x] Create temporary REPL contract (in memory, or temp file?).
    - [x] Implement `forge-std/Test.sol` so that cheatcodes, etc. can be used.
  - [x] Utilize foundry's `evm` module for REPL env.
    - [x] Implement network forking.
  - [x] Expression evaluation / inspection (i.e. the input `0x01 << 0x08` should inspect a `uint` of value `256`)
    - [x] Support for primitive type expressions (i.e. primitive types, arithmetic ops, bitwise ops, boolean ops, global vars (`msg`, `tx`, `block`, & `abi`))
    - [x] Support for function call expressions (both local and external to the REPL contract)
    - [x] Support for array indexing (external + local)
    - [x] Support for mapping indexing (external + local)
    - [x] Clean up refactor
  - [x] Input history.
  - [x] Use forge fmt module to format source code when printing via the `!source` command or exporting to a Script file (?)
- [x] Cache REPL History
  - [x] Allow a user to save/load sessions from their Chisel history.
    - [x] Fix session loading bug wrt non-serializable `IntermediateOutput` component.
- [ ] Custom commands / cmd flags / etc.
  - [x] Inspect variable
    - [x] Inspect raw stack
  - [x] Inspect memory vars
    - [x] Inspect raw memory
  - [x] Inspect storage vars
    - [ ] Inspect raw storage slots / storage layout
  - [ ] Inspection verbosity configuration
  - [ ] Undo
  - [ ] Inspect bytecode / mnenomic of local or remote contracts.
    - [ ] Possibly use the forge debugger for this?
  - [x] Fetch contract interface from Etherscan ABI
  - [ ] Import remote sources from GitHub
  - [x] Enable / disable call trace printing
    - [x] Rip trace printing code from another module of foundry.
  - [x] On-the-fly network forking
  - [x] Export to file
    - [x] Export session to script contract if within project.
- [x] [Syntax highlighting](https://docs.rs/rustyline/10.0.0/rustyline/highlight/trait.Highlighter.html)
- [x] Binary subcommands
- [x] Tests.
  - [x] Cache
- [x] Benchmarks.
  - [x] Session Source
    - [x] Building
    - [x] Executor
    - [x] Inspection
    - [x] Cloning
- [ ] Optimizations (after MVP).
  - [ ] Speed up REPL execution time.
    - [ ] Use flamegraph to determine plan of attack.
    - [ ] Rework SessionSource clone, does not need to be a full deep copy.
    - [ ] Cache the backend within the executor so that it is not regenerated on each run. This causes lag with forks especially. We should keep the option to refresh each time to keep live state, but disable this by default.
- [x] Finish README.
  - [x] Examples
  - [x] Migration from existing REPLs
- [ ] First review.
  - [x] Support ENV var interpolation in fork urls
  - [x] Allow named sessions
  - [x] Rename `!flush` to `!save`
  - [x] Check fork URL validity
  - [x] Add builtin command shorthands
  - [ ] ...

**Comment by joshieDo** [comment]
feature request: execute a script and start the shell at the end of it :point_right: :point_left: 
`chisel script/script.sol`

**Comment by transmissions11** [comment]
Crossposting some of my chisel feature request here:
# feat(chisel): display raw stack values when logging variable

### Describe the feature you would like

Currently with <32 byte types, their higher order bits aren't shown anywhere except the stackdump. Often when I'm fooling around with assembly I want to see the full in-stack representation of these types (higher order bits and all), so would be great if there was an additional field in the variable output like `Raw: 0x1000000000000000000000000000000000000000000000000000000000000002` so we could easily observe these things. Another option would be a `!raw [var]`-esque command.

Here are some repro cases of higher order bits not being shown.

```solidity
λ chisel
Welcome to Chisel! Type `!help` to show available commands.

➜ uint16 num = 2;
➜ assembly { num := 0x1000000000000000000000000000000000000000000000000000000000000002 }
➜ num
Type: uint
├ Hex: 0x2
└ Decimal: 2
➜ !sd
[0]: 0x1000000000000000000000000000000000000000000000000000000000000002
[1]: 0x33
[2]: 0xc0406226

➜ address addy = address(0xBEEF);
➜ assembly { addy := 0x100000000000000000000000000000000000000000000000000000000000beef }
➜ addy
Type: address
└ Data: 0x000000000000000000000000000000000000beef
➜ !sd
[0]: 0x100000000000000000000000000000000000000000000000000000000000beef
[1]: 0x33
[2]: 0xc0406226
```

### Additional context

_No response_

**Comment by ItosTerence** [comment]
### Feature Request: Gas Reporting Per Line

After you run a command, it'd be great to see the gas cost of what you just ran.
