### ISSUE TITLE
meta(abstract): post V1 planning

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5215]
### Mission-critical rewrites
- [ ] Library Linking Rewrite
- [ ] Scripting Rewrite & Multi-chain enhancements
- [ ] Book updates with better tutorials

### Features to maintain
- [ ] `evm` crate (refactor to dedupe code)
- [ ] Improve debugger readability & maintainability
- [ ] JSON Parsing

### New features
- [ ] Gain access to `JUMPI` hooks for more granular and enhanced cheatcodes

**Comment by WEI-NERD** [comment]
Cooooooooooking god.

**Comment by zerosnacks** [comment]
Closing in favor of https://github.com/foundry-rs/foundry/issues/8574, will be incorporated there
