### ISSUE TITLE
meta(`gas reporting`): gas reporting tracker

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5354]
## Gas reporting improvements tracker
- [ ] do not include gas usage from setUp()
- [ ] do not include base+calldata+access list costs
- [ ] fix accounting for cold/warm addresses
- [ ] fix accounting for cold/warm storage slots
- [ ] fix accounting for SSTORE refunds due to all of the above

As reported in [tweet](https://twitter.com/emo_eth/status/1678569632410779648) and adjacent conversation.

**Comment by Evalir** [comment]
This was mostly fixed with the `--isolate` flag.
