### ISSUE TITLE
Checklist of things that need to be done

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#536]
Quick braindump of things we should do in terms of docs / PM moving forward

* [x] FAQ Doc
    * [x] foundryup vs cargo/bin installation path (either delete the .cargo/bin or set .foundrup/bin before it in your PATH)
    * [x] i cannot see my logs (need to trigger verbosity)
    * [x] how do I fork mainnet state? (--fork-url)
    * [x] how do gas snapshots work?
    * [x] how do I use a manual solc version? (--offline / --no-auto-detect / SOLC_PATH / PATH)
    * [x] how to use console.sol (need to vendor it)
    * [x] how do I run specific tests / contracts? (--match / --match-contract etc.)
* [x] Patterns doc
    * [x] using cheatcodes
    * [x] reusable test suites (https://github.com/gakonst/foundry/issues/407#issuecomment-1008291455)
    * [x] discarding fuzzed inputs
* [x] Known Issues Doc
  * [x] caching bug
  * [x] fuzzer edge cases
  * [x] missing libusb
* [x] Improved Issue Template
  * [x] How did you install foundry?
  * [x] What is the exact set of commands that you ran to get the bug? 
  * [x] If it's a Solidity repo, do you have a minimal code example?
  * [x] Did you check the FAQ?
  * [x] Is this a Foundry question, or are you making a Solidity mistake?
* [x] PR Template
  * [x] Motivation
  * [x] Solution
* [ ] Projects
  * [x]  Deploy
  * [x] Etherscan Verification
  * [ ] Symbolic EVM
  * [x] Improved Fuzzer
  * [ ] Mutation Testing
  * [x] Coverage
  * [x] Gas Reports
  * [ ] Refactor to be abstract over Compiler and Runtime (set up StarkNet support)
  * [ ] Solidity Book using Foundry
  * [x] Foundry Book
 

What else are we missing?

**Comment by mattsse** [comment]
meta:
- [ ] add Architecture.md
- [ ] add Contributing.md

pending features
- [ ] solidity formatter #201
- [ ] solidity repl #230 #240
- [ ] detect minimum supported solc version #391

**Comment by alephao** [comment]
On the `FAQ doc`, any idea on how that should be structured? Just dump on `README.md` for now and figure out later?

Happy to work on those to help out:
- [ ] how do I run specific tests / contracts? (--match / --match-contract etc.)
- [ ] i cannot see my logs (need to trigger verbosity)

**Comment by onbjerg** [comment]
- [ ] Debugging for tests with parameters (to debug fuzz tests)

**Comment by mds1** [comment]
A few other things I'd find useful that I'd like to be on this list:
- A `vm.not` cheatcode, or more discussion on whether it's needed / there's existing workarounds we haven't thought of: https://github.com/gakonst/foundry/issues/509
- Modifying how `expectEmit` works for more flexibility / stronger assertions: https://github.com/gakonst/foundry/issues/512#issuecomment-1016577046
- There's a few other fuzzer patterns we can discuss such as bounding inputs and converting "bad" inputs to good ones
- Based on https://github.com/gakonst/foundry/issues/432, it seems mocking responses from a jump isn't practical. This means `mockCall` and `expectCall` work on for methods invoked via calls, not jumps. Having those methods behave the same regardless of how the function was invoked would be very helpful, and would result in less unexpected behavior (e.g. I mock response to `A.foo()` and now get hard to debug test failures because `A.foo()` gives different responses when called by `A` vs `B`
- RPC functionality is a big one https://github.com/gakonst/foundry/pull/174

**Comment by onbjerg** [comment]
The fix for `mockCall` would require a rewrite to use revm over Sputnik which is a big task

**Comment by EricForgy** [comment]
> What else are we missing?

Maybe a VS Code extension? 

I was happy to learn about foundry.toml and put my remappings in there. It compiles and runs fine, but VS Code doesn't yet recognize the remappings (red triggering squiggles) and putting them in workspace settings doesn't feel great. I ended up moving back to remappings.txt temporarily.

**Comment by bbonanno** [comment]
Filesystem cache when running on a fork from mainnet (like hardhat), the amount of RPC requests and the time that it takes when iterating over a test is quite significant (currently >60s on some test I'm working on).
For what I can see there's an in-memory cache so running a full test suite doesn't get that bad, but when writing a test you normally have to run it many times so it gets annoying to wait 30s or more each time.

**Comment by appleseed-iii** [comment]
what do you think about removing the leading substring `Address: ` from the `cast wallet address` command https://github.com/foundry-rs/foundry/blob/7257375f8c039727ac565038e074ed2e547e604a/cli/src/cmd/cast/wallet/mod.rs#L136? The leading substring makes the command a little more painful to chain & seems unnecessary.

I haven't gotten far enough to see if there are other places this pattern exists.

**Comment by mattsse** [comment]
makes sense, @appleseed-iii 

feel free to open a PR

**Comment by paulrberg** [comment]
Can we add [table tests](https://github.com/foundry-rs/foundry/issues/858) to this checklist?

I think that it's a very important feature that it's currently missing from Forge.

**Comment by ChainsightLabs** [comment]
> Can we add [table tests](https://github.com/foundry-rs/foundry/issues/858) to this checklist?
> 
> I think that it's a very important feature that it's currently missing from Forge.

Yes, table tests please!

**Comment by h0tw4t3r** [comment]
> > What else are we missing?
> 
> Maybe a VS Code extension?
> 
> I was happy to learn about foundry.toml and put my remappings in there. It compiles and runs fine, but VS Code doesn't yet recognize the remappings (red triggering squiggles) and putting them in workspace settings doesn't feel great. I ended up moving back to remappings.txt temporarily.

Makes even more sense to make a separate Language Server, as there is only vscode-s one that cannot be even used in `vim`.

**Comment by y1cunhui** [comment]
Hello, I'm wondering what does "Solidity Book using Foundry" means? I 'm interested in this topic and willing to finish this

**Comment by milaabl** [comment]
@y1cunhui , probably something like a Solidity development with Foundry guidelines book? Not sure

**Comment by ennioVisco** [comment]
`foundryup` runnable natively on Windows

**Comment by zerosnacks** [comment]
Closing as open checkboxes have their individual follow-up tickets or are top of mind:

- https://github.com/foundry-rs/foundry/issues/15
- https://github.com/foundry-rs/foundry/issues/478
- https://github.com/foundry-rs/compilers + https://github.com/foundry-rs/starknet-foundry
