### ISSUE TITLE
meta: Foundry Cancun readiness

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5574]
## Motivation

Foundry Cancun tracking issue for readiness.

## Items needed
- [x] `revm` foundry upgrade #5669 
- [x] `revm` EIP-4844 support: https://github.com/bluealloy/revm/pull/536
- [x] `revm` alloy migration: https://github.com/bluealloy/revm/issues/527
- [x] `alloy` EIP-4844 support.

## Anvil
- [x] EIP-4844 type support on Anvil & corresponding revm config: https://github.com/foundry-rs/foundry/pull/7202
- [x] Ensure `send/send_raw_transaction` methods can properly decode 4844 txs. https://github.com/alloy-rs/alloy/pull/229
- [x] Change `TransactionExecutor` to validate 4844 txs iff cancun spec is active https://github.com/foundry-rs/foundry/pull/7242
- [x] Adjust new / changed RPC methods accordingly: https://github.com/foundry-rs/foundry/pull/7242

## Forge
- [x] `vm.blobhashes`: https://github.com/foundry-rs/foundry/pull/7001

## Cast
- [x] `cast send` 4844 support https://github.com/foundry-rs/foundry/pull/7823

**Comment by rakita** [comment]
Here is meta issue for revm: https://github.com/bluealloy/revm/issues/527

**Comment by Evalir** [comment]
Thank you @rakita! Was wondering, do you have any ETAs for when will `revm` be ready for cancun? Anything I can do to help drive it to completion?

**Comment by Rjected** [comment]
bump on this, everything should be fine on the revm side, but rpc types might need to be adjusted? In particular anvil would need blob support for `eth_sendTransaction` and raw tx + blob decoding, which are currently implemented in reth. Not sure what the best way is to share, for example, the RLP decoding if anvil were to accept blob transactions with a sidecar on a forked network

**Comment by Thegaram** [comment]
Hi @Evalir, do you have an estimate as to when forge and anvil will support blob transactions? Currently there's no good tool to unit test features that rely on blobs.

**Comment by Evalir** [comment]
Almost @Thegaram — the last missing piece is https://github.com/foundry-rs/foundry/pull/7823

**Comment by zerosnacks** [comment]
Closing as https://github.com/foundry-rs/foundry/pull/7823 has been merged
