### ISSUE TITLE
Sputnik-blocked issues

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#654]
A list of issues that are hard to solve because of how Sputnik works:

**VM errors**

These are hard to solve because the error message we really want is somewhere deep in Sputnik's `Machine` that we have no control over. Usually the error just gets converted from an `ExitReason::Error(ExitError)` to an `ExitReason::Revert(ExitRevert)`.

- [x] https://github.com/gakonst/foundry/issues/499
- [x] https://github.com/gakonst/foundry/issues/476

**Cheatcodes**

- [ ] https://github.com/gakonst/foundry/issues/432: Can only be solved by changing the control flow of the EVM, which again, requires us to fork `Machine`

**Comment by brockelmore** [comment]
correction: we can hack around the `mockCall` limitation like how we do for debugging

**Comment by gakonst** [comment]
Fixed #1 in https://github.com/gakonst/foundry/commit/809500f52bde1a7ec082ce76bfd506a55bf2ea44

**Comment by mattsse** [comment]
closing since this is sputnik related which was phased out
