### ISSUE TITLE
meta(anvil): `anvil-core` internal types removal

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#6715]
The objective is to deduplicate the internal anvil types in `anvil-core`, used for storage and internal representation of state and phase out ethers. This involves:
- Removing the duplicated types in `anvil-core` which are now included in https://github.com/alloy-rs/alloy/pull/83
- Using the new alloy signers
- Migrating any custom needed anvil internal types (e.g `ImpersonatedTransaction`) to alloy.
- Migrating anvil's txpool/execution logic to use alloy.

Milestones on (`anvil-core`/`anvil`):
- [x] `ethers_compat.rs` phased out
- [x] `block.rs` phased out as duplicate
- [x] `pubsub.rs` phased out as duplicate https://github.com/foundry-rs/foundry/pull/6775
- [x] `state.rs` phased out as duplicate https://github.com/foundry-rs/foundry/pull/6766
- [x] `cheats.rs` cheats manager migrated https://github.com/foundry-rs/foundry/pull/6767
- [x] `receipt.rs` phased out as duplicate by using the new receipt type in Alloy Consensus
- [x] `subscription.rs` types migrated to use alloy-rpc types, consensus or core types wherever needed
- [x] `trie.rs` migrated (migration needed for `eth_getProof` endpoint)
- [x] `utils.rs` migrated to using alloy rlp encoding instead of parity rlp.
- [x] `anvil`'s `executor.rs` migrated to use alloy types.
- [x] all `ToAlloy/ToEthers` conversions in anvil removed
- [x] `fastrlp` dropped
- [x] ethers removed from tests.

The result of this is that we will end up removing all the remaining `ToAlloy`/`ToEthers` conversions in anvil, as we won't longer have the separation between alloy-based rpc types and ethers-based internal types, but rather both will come from `alloy-rs/alloy`, and use the alloy primitive types. This allows us to drop ethers completely from anvil

**Comment by Evalir** [comment]
Closing as this is strictly related to `anvil-core`—the only work remaining is on the main anvil crate, for tests.
