### ISSUE TITLE
meta(`1.0`): tracking issue for `1.0` milestone

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#7613]
- [ ] Create `1.0` upgrade guide
- [ ] https://github.com/foundry-rs/foundry/issues/7238
- [ ] https://github.com/foundry-rs/foundry/issues/7237

**Comment by mattsse** [comment]
closing as outdated
