### ISSUE TITLE
Fuzzer Meta

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#8076]
[https://twitter.com/gakonst/status/1790770389523583163](https://twitter.com/gakonst/status/1790770389523583163)

**Comment by zerosnacks** [comment]
this would be neat: https://github.com/foundry-rs/foundry/issues/4000

**Comment by grandizzy** [comment]
> this would be neat: #4000

yep, indeed! made a PR for it here https://github.com/foundry-rs/foundry/pull/8338

**Comment by 0xalpharush** [comment]
Following up on https://github.com/foundry-rs/foundry/pull/10190

- [ ] share corpus and run as many invariants in as many threads as possible https://github.com/foundry-rs/foundry/issues/8898
 - [ ] Updated "favored" entries in corpus to retain all unique edges https://github.com/foundry-rs/foundry/pull/11769#discussion_r2374142332 https://github.com/foundry-rs/foundry/pull/12971
 - [ ] Add swarm testing mode that runs with variable configs in each thread i.e. different sequence length, weights, other tunable fuzzing configs 
- [ ] ignore crashes to allow continuous fuzzing https://github.com/foundry-rs/foundry/issues/9727
- [x] campaign stats logging https://github.com/foundry-rs/foundry/issues/10876
    - [ ] add gas/s
- [x] stateless fuzzing support and additional ABI mutations https://github.com/foundry-rs/foundry/issues/10877
- [x] fuzz msg.value https://github.com/foundry-rs/foundry/pull/14565
    - [ ] Add ABI value shrinking and msg.value shrinking to shrink implementation
- [ ] seed corpus from tests https://github.com/foundry-rs/foundry/issues/10875
- [x] insert constants and evaluated constant expressions in source in to fuzzer dictionary https://github.com/foundry-rs/foundry/issues/10233


### Future work
- [ ] Trace EVM comparison opcodes and implement REDQUEEN/cmplog colorization to try and solve comparisons
- [ ] Snapshot states like ityfuzz and explore from different points in tree instead of fixed-depth sequences
- [ ] implement compile-time, non-colliding instrumentation like afl++ PCGUARD in Solar and coverage-guided fuzzing to use it
