### ISSUE TITLE
meta(anvil): tracking issue for Anvil improvements

### ISSUE THREAD

**Issue by zerosnacks** [foundry-rs/foundry#8269]
### Component

Anvil

### Describe the feature you would like

Tracking improvements for Anvil:

Tracking improvements for Anvil:

## Features

- [ ] https://github.com/foundry-rs/foundry/issues/1505
- [ ] https://github.com/foundry-rs/foundry/issues/8227
- [ ] https://github.com/foundry-rs/foundry/issues/6764
- [ ] https://github.com/foundry-rs/foundry/issues/2806
- [ ] https://github.com/foundry-rs/foundry/issues/3112
- [ ] https://github.com/foundry-rs/foundry/issues/3788
- [ ] https://github.com/foundry-rs/foundry/issues/4110
- [ ] https://github.com/foundry-rs/foundry/issues/4129
- [ ] https://github.com/foundry-rs/foundry/issues/4240
- [ ] https://github.com/foundry-rs/foundry/issues/4360
- [ ] https://github.com/foundry-rs/foundry/issues/4585

## Configuration

- [ ] https://github.com/foundry-rs/foundry/issues/4226
- [ ] https://github.com/foundry-rs/foundry/issues/7442
- [ ] https://github.com/foundry-rs/foundry/issues/7901
- [ ] https://github.com/foundry-rs/foundry/issues/3512
- [ ] https://github.com/foundry-rs/foundry/issues/3783

## Caching

- [ ] Compression of cache? (polars?)
- [ ] https://github.com/foundry-rs/foundry/issues/1759
- [ ] https://github.com/foundry-rs/foundry/issues/4251

## Bugs

- [ ] https://github.com/foundry-rs/foundry/issues/4843
- [ ] https://github.com/foundry-rs/foundry/issues/1819
- [ ] https://github.com/foundry-rs/foundry/issues/3478
- [ ] https://github.com/foundry-rs/foundry/issues/3840
- [ ] https://github.com/foundry-rs/foundry/issues/4050
- [ ] https://github.com/foundry-rs/foundry/issues/4094
- [ ] https://github.com/foundry-rs/foundry/issues/4173
- [ ] https://github.com/foundry-rs/foundry/issues/4323
- [ ] https://github.com/foundry-rs/foundry/issues/4327
- [ ] https://github.com/foundry-rs/foundry/issues/4340
- [ ] https://github.com/foundry-rs/foundry/issues/4490
- [ ] https://github.com/foundry-rs/foundry/issues/4700

## Chores

- [ ] https://github.com/foundry-rs/foundry/issues/6860
- [ ] https://github.com/foundry-rs/foundry/issues/7048

## Other

- [ ] https://github.com/foundry-rs/foundry/issues/6440
- [ ] https://github.com/foundry-rs/foundry/issues/2930
- [ ] https://github.com/foundry-rs/foundry/issues/4246
