### ISSUE TITLE
meta: new cheatcodes and cheatcode enhancements

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#876]
### Component

Forge

### Describe the feature you would like

Aggregating a list of new cheatcodes and improvements to existing cheatcodes that have been requested in other issues:

- [ ] 1. `vm.not` cheat code. When called immediately before (or after?) `expectEmit` or `expectCall` it modifies that cheat code so the event/call is expected not to be present. Alternatively, `expectNoEmit` or `expectNoCall` would work. https://github.com/gakonst/foundry/issues/509
- [ ] 2. Allow `expectEmit` to be declared _after_ the call emitting the event, instead of the current workflow which requires it to be declared before. If we have to choose only allowing it to be declared before or after, my preference would be after, because it allows you to read updated state from the call and use those values as the event args, as explained  in https://github.com/gakonst/foundry/issues/512#issuecomment-1016577046
- [ ] 3. Update `mockCall`, `expectCall`, and `expectRevert` (and `expectEmit`?) to work for JUMPs (currently they only work for calls). This has been discussed in #432 and #864
- [ ] 4. When an `expectEmit` matcher fails, specify which topics or data did not match: https://github.com/gakonst/foundry/issues/592
- [x] 5. Some `expectEmit` issues described in https://github.com/gakonst/foundry/issues/760
- [ ] 6. Still needs more discussion to determine if cheatcodes is the optimal approach, but I think cheatcodes for setting fuzzer params on a per-contract or per-test basis would be very useful: https://github.com/gakonst/foundry/issues/744
- [x] 7. Nonce cheatcodes: https://github.com/gakonst/foundry/issues/554
- [x] 8. `captureLogs` and `getLogs` cheatcodes (similar to `records` and `accesses`) to support https://github.com/gakonst/foundry/issues/543
- [x] 9. `vm.roll` should update how RPC queries behave when forking: https://github.com/gakonst/foundry/issues/939
- [ ] 10. `expectEmit` error message: https://github.com/gakonst/foundry/issues/908
- [x] 11. `expectRevert` with no bytes to assert that any revert should happen: https://github.com/gakonst/foundry/issues/885
- [ ] 12. Needs discussion/decision, but requiring `expectEmit`/`expectCall` to only check the next call, and not all subsequent calls: https://github.com/foundry-rs/foundry/issues/1745
- [ ] 13. Some `expect*` edge cases / bugs? https://github.com/foundry-rs/foundry/issues/3723#issuecomment-1323696016

**Comment by onbjerg** [comment]
Another issue we should investigate (not sure if it makes sense): https://github.com/gakonst/foundry/issues/824

Quality of life issues:
- `expectEmit` error message: https://github.com/gakonst/foundry/issues/908
- `expectRevert` with no bytes to assert that any revert should happen: https://github.com/gakonst/foundry/issues/885

**Comment by brockelmore** [comment]
9. we should just overload roll to add a bool whether to update fork block number

**Comment by mds1** [comment]
> we should just overload roll to add a bool whether to update fork block number

Ah yea I like that, more flexibility than a flag that applies to the full test suite 👌

**Comment by onbjerg** [comment]
- `vm.skip` https://github.com/foundry-rs/foundry/issues/1123

**Comment by 0xmikko** [comment]
Please, add `expectNoCall` and `expectNoEmit` to check that no calls or events were done. 
No we have to develop `bicycles`to cover such problems

**Comment by Van0k** [comment]
`expectNoCall` and `expectNoEmit` are sorely needed.
Also, while this is not strictly about cheatCodes, parametrizable setUp() for fuzzed deployment would be really useful.

**Comment by onbjerg** [comment]
Please open up issues regarding all of the features listed above so we can track them separetely

**Comment by adhusson** [comment]
Another nice addition would be `expectRevert(bytes,string)` where the string is an error message displayed if the next call does not revert.

**Comment by mds1** [comment]
Closing this tracking issue in favor of #4439
